# Generated by Django 5.2.1 on 2025-07-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=models.TextField(blank=True, verbose_name='Post Markdown content'),
        ),
    ]
